builds:
- main: ./byhash.go
  binary: byhash
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
  - linux
  - darwin
  goarch:
  - amd64

archives:
  name_template: "byhash_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: macOS
  wrap_in_directory: true
  files:
    - none*

release:
  github:
    owner: limikmag
    name: golang
  name_template: "byhash v{{.Version}}"
