builds:
- env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  goos:
    - linux
  id: byhash
  main: ./byhash.go
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
    - byhash
    skip_push: false
