
language: go
sudo: false
dist: xenial
go: 1.13.5
os:
- linux
git:
  depth: 1
install: true
before_script:
  - go mod tidy -v
  
deploy:
- provider: script
  skip_cleanup: true
  script: bash goreleaser.sh
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
